### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "fix windows"
keywords:    "windows"
description: "How to make your windows installation more functional."
source_link: "https://github.com/Shivanshi1729/fix_windows"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"

### template colors, used site-wide via css ###
colors:
  black:     '#2e3440'
  white:     '#eceff4'
  shade1:    '#8fbcbb'
  shade2:    '#88c0d0'
  shade3:    '#81a1c1'
  shade4:    '#5e81ac'
  shade5:    '#3b4252'
  shade6:    '#434c5e'
  shade7:    '#4c566a'


kramdown:
  auto_ids:  false